language: python
services:
  - postgresql
  - redis-server
python:
  - "2.7"
before_script:
- export DATABASE_URL=postgres://postgres@localhost/geopolls-rest
- export DJANGO_SECRET=`openssl rand -base64 32`
- psql -c 'CREATE DATABASE "geopolls-rest";' -U postgres
install:
  - "pip install -r requirements/test.txt"
script:
  - ./geopolls-rest/manage.py test geopolls-rest
after_success:
  - coveralls

deploy:
  provider: heroku
  app:
    master: geopolls-rest-dev
    qa: geopolls-rest-qa
    prod: geopolls-rest-prod
  on:
    repo: easherma/geopolls-rest
  run:
    - "./geopolls-rest/manage.py migrate"

notifications:
  email: false

# This reportedly works around an issue downloading packages from pypi on
# travis. Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false

matrix:
  fast_finish: true

cache: pip
